package:
  name: tomobase
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install -e ."

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - matplotlib
    - scipy
    - imageio
    - progress
    - h5py
    - mrcz
    - makefun
    - qtpy
    - magicgui
    - pandas
    - colorama
    - plotly
    - skimage

channels:
  - defaults
  - conda-forge


about:
  home: https://github.com/Tcraig088/tdtomonapari
  license: GPL3.0
  license_family: GPL
  summary: A library for running time-dependent tomography modules in napari
  description: |
    A library for running time-dependent tomography modules in napari.
  license_file: ../LICENSE

extra:
  recipe-maintainers:
    - Tcraig088